# Generated by Django 2.2.6 on 2019-11-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='datafield',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='community.DataFieldType'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='wikidata_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='community.WikidataItem'),
        ),
    ]
