# Generated by Django 2.2.6 on 2019-11-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191110_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='wikidata_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='community.WikidataItem'),
        ),
    ]
