# Generated by Django 2.2.6 on 2019-11-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='data_fields',
            field=models.ManyToManyField(to='community.DataField'),
        ),
    ]
