# Generated by Django 2.2.6 on 2019-11-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20191110_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('image_path', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('image_path', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='community.User')),
                ('members', models.ManyToManyField(related_name='member', to='community.User')),
            ],
        ),
        migrations.AddField(
            model_name='datafield',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
        ),
    ]
