# Generated by Django 2.2.6 on 2019-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20191110_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
