# Generated by Django 2.2.6 on 2019-11-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20191110_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('upvote_count', models.IntegerField()),
                ('downvote_count', models.IntegerField()),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.DataType')),
            ],
        ),
    ]
