# Generated by Django 2.2.6 on 2019-11-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
        ),
    ]
