# Generated by Django 2.2.6 on 2019-11-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_fieldvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalue',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='field_values',
            field=models.ManyToManyField(to='community.FieldValue'),
        ),
    ]
