# Generated by Django 2.2.6 on 2019-11-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20191116_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
            preserve_default=False,
        ),
    ]
