# Generated by Django 2.2.6 on 2019-11-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='community.Community'),
            preserve_default=False,
        ),
    ]
