# Generated by Django 2.2.6 on 2019-11-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20191116_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldvalue',
            old_name='Post',
            new_name='post',
        ),
    ]
