# Generated by Django 2.2.6 on 2019-11-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_auto_20191116_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='community',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='type',
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='wikidata_item',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='community',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='data_fields',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='data_field',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.RemoveField(
            model_name='post',
            name='data_type',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='DataField',
        ),
        migrations.DeleteModel(
            name='DataFieldType',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.DeleteModel(
            name='FieldValue',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WikidataItem',
        ),
    ]
