# Generated by Django 2.2.6 on 2019-11-16 12:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0021_auto_20191116_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikidataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
