# Generated by Django 2.2.6 on 2019-11-16 13:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_wikidataitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidataitem',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
