# Generated by Django 2.2.6 on 2019-11-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_auto_20191116_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('is_required', models.BooleanField()),
                ('wikidata_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.WikidataItem')),
            ],
        ),
    ]
