# Generated by Django 2.2.6 on 2019-11-16 18:03

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=community.models.PathAndRename('images')),
        ),
    ]
