# Generated by Django 2.2.6 on 2019-11-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_auto_20191117_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('a', 'admin'), ('s', 'standard')], max_length=1)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.User')),
            ],
        ),
    ]
