# Generated by Django 2.2.6 on 2019-11-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_auto_20191117_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('community', 'user')},
        ),
    ]
