# Generated by Django 2.2.6 on 2019-11-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_auto_20191117_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='members', through='community.Membership', to='community.User'),
        ),
    ]
