# Generated by Django 2.2.6 on 2019-11-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_auto_20191120_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='community.User')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
