# Generated by Django 2.2.6 on 2019-11-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_auto_20191120_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
