# Generated by Django 2.2.6 on 2019-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0040_datatype_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
