# Generated by Django 2.2.6 on 2019-11-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_community_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
