# Generated by Django 2.2.6 on 2019-11-24 12:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0044_post_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='fields',
        ),
        migrations.AddField(
            model_name='datatype',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DataField',
        ),
    ]
