# Generated by Django 2.2.6 on 2019-11-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0045_auto_20191124_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
