# Generated by Django 2.2.6 on 2019-11-24 16:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0046_datatype_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
